# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MachineLearning.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MachineLearning(object):
    def setupUi(self, MachineLearning):
        MachineLearning.setObjectName("MachineLearning")
        MachineLearning.resize(1440, 855)
        self.mlp_frame = QtWidgets.QFrame(MachineLearning)
        self.mlp_frame.setGeometry(QtCore.QRect(410, 50, 471, 531))
        self.mlp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mlp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mlp_frame.setObjectName("mlp_frame")
        self.label_6 = QtWidgets.QLabel(self.mlp_frame)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mlp_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 451, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mlp_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mlp_plot.setContentsMargins(0, 0, 0, 0)
        self.mlp_plot.setObjectName("mlp_plot")
        self.frame = QtWidgets.QFrame(MachineLearning)
        self.frame.setGeometry(QtCore.QRect(10, 130, 391, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.process_selection = QtWidgets.QComboBox(self.frame)
        self.process_selection.setGeometry(QtCore.QRect(10, 40, 311, 26))
        self.process_selection.setObjectName("process_selection")
        self.process_selection.addItem("")
        self.process_selection.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.label_7.setObjectName("label_7")
        self.parameter_frame = QtWidgets.QFrame(MachineLearning)
        self.parameter_frame.setGeometry(QtCore.QRect(10, 50, 391, 71))
        self.parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameter_frame.setObjectName("parameter_frame")
        self.label_load_3 = QtWidgets.QLabel(self.parameter_frame)
        self.label_load_3.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_load_3.setObjectName("label_load_3")
        self.label_4 = QtWidgets.QLabel(self.parameter_frame)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_4.setObjectName("label_4")
        self.sample_frequency = QtWidgets.QComboBox(self.parameter_frame)
        self.sample_frequency.setGeometry(QtCore.QRect(120, 30, 104, 26))
        self.sample_frequency.setObjectName("sample_frequency")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.files_frame = QtWidgets.QFrame(MachineLearning)
        self.files_frame.setGeometry(QtCore.QRect(10, 300, 391, 121))
        self.files_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.files_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.files_frame.setObjectName("files_frame")
        self.label_load = QtWidgets.QLabel(self.files_frame)
        self.label_load.setGeometry(QtCore.QRect(10, 20, 76, 16))
        self.label_load.setObjectName("label_load")
        self.btn_load_file = QtWidgets.QPushButton(self.files_frame)
        self.btn_load_file.setGeometry(QtCore.QRect(120, 10, 261, 32))
        self.btn_load_file.setObjectName("btn_load_file")
        self.btn_save_model = QtWidgets.QPushButton(self.files_frame)
        self.btn_save_model.setGeometry(QtCore.QRect(220, 80, 161, 32))
        self.btn_save_model.setObjectName("btn_save_model")
        self.echo_file_name = QtWidgets.QLineEdit(self.files_frame)
        self.echo_file_name.setGeometry(QtCore.QRect(170, 50, 201, 21))
        self.echo_file_name.setObjectName("echo_file_name")
        self.label = QtWidgets.QLabel(self.files_frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label.setObjectName("label")
        self.btn_train = QtWidgets.QPushButton(self.files_frame)
        self.btn_train.setGeometry(QtCore.QRect(80, 80, 141, 32))
        self.btn_train.setObjectName("btn_train")
        self.random_forest_frame = QtWidgets.QFrame(MachineLearning)
        self.random_forest_frame.setGeometry(QtCore.QRect(890, 50, 481, 531))
        self.random_forest_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.random_forest_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.random_forest_frame.setObjectName("random_forest_frame")
        self.label_9 = QtWidgets.QLabel(self.random_forest_frame)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.random_forest_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 461, 491))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.rf_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.rf_plot.setContentsMargins(0, 0, 0, 0)
        self.rf_plot.setObjectName("rf_plot")
        self.table_widget = QtWidgets.QTableWidget(MachineLearning)
        self.table_widget.setGeometry(QtCore.QRect(10, 430, 401, 291))
        self.table_widget.setMinimumSize(QtCore.QSize(401, 0))
        self.table_widget.setMaximumSize(QtCore.QSize(401, 16777215))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(6)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(5, item)
        self.machine_learning_method = QtWidgets.QFrame(MachineLearning)
        self.machine_learning_method.setGeometry(QtCore.QRect(10, 220, 391, 71))
        self.machine_learning_method.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.machine_learning_method.setFrameShadow(QtWidgets.QFrame.Raised)
        self.machine_learning_method.setObjectName("machine_learning_method")
        self.label_5 = QtWidgets.QLabel(self.machine_learning_method)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 271, 16))
        self.label_5.setObjectName("label_5")
        self.trainSize = QtWidgets.QSlider(self.machine_learning_method)
        self.trainSize.setGeometry(QtCore.QRect(110, 10, 251, 22))
        self.trainSize.setOrientation(QtCore.Qt.Horizontal)
        self.trainSize.setObjectName("trainSize")
        self.txt_train_size = QtWidgets.QLineEdit(self.machine_learning_method)
        self.txt_train_size.setGeometry(QtCore.QRect(140, 40, 211, 21))
        self.txt_train_size.setObjectName("txt_train_size")
        self.btn_data_open = QtWidgets.QPushButton(MachineLearning)
        self.btn_data_open.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.btn_data_open.setObjectName("btn_data_open")
        self.btn_ml_prediction_open = QtWidgets.QPushButton(MachineLearning)
        self.btn_ml_prediction_open.setGeometry(QtCore.QRect(450, 10, 251, 32))
        self.btn_ml_prediction_open.setObjectName("btn_ml_prediction_open")
        self.btn_ml_open = QtWidgets.QPushButton(MachineLearning)
        self.btn_ml_open.setGeometry(QtCore.QRect(220, 10, 241, 32))
        self.btn_ml_open.setObjectName("btn_ml_open")

        self.retranslateUi(MachineLearning)
        QtCore.QMetaObject.connectSlotsByName(MachineLearning)

    def retranslateUi(self, MachineLearning):
        _translate = QtCore.QCoreApplication.translate
        MachineLearning.setWindowTitle(_translate("MachineLearning", "MachineLearning"))
        self.label_6.setText(_translate("MachineLearning", "MLP Confusion Matrix"))
        self.process_selection.setItemText(0, _translate("MachineLearning", "Train Model Human Non Human"))
        self.process_selection.setItemText(1, _translate("MachineLearning", "Train Model Other Objects"))
        self.label_7.setText(_translate("MachineLearning", "Selection"))
        self.label_load_3.setText(_translate("MachineLearning", "Initial Parameters"))
        self.label_4.setText(_translate("MachineLearning", "Echo size"))
        self.sample_frequency.setItemText(0, _translate("MachineLearning", "2.86MHz"))
        self.sample_frequency.setItemText(1, _translate("MachineLearning", "1.14MHz"))
        self.sample_frequency.setItemText(2, _translate("MachineLearning", "114KHz"))
        self.label_load.setText(_translate("MachineLearning", "Select File"))
        self.btn_load_file.setText(_translate("MachineLearning", "Load Files"))
        self.btn_save_model.setText(_translate("MachineLearning", "Save Model"))
        self.label.setText(_translate("MachineLearning", "Model file name"))
        self.btn_train.setText(_translate("MachineLearning", "Start Training"))
        self.label_9.setText(_translate("MachineLearning", "Random Forest Confusion Matrix"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MachineLearning", "Label"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MachineLearning", "Total"))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MachineLearning", "Train"))
        item = self.table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MachineLearning", "Test"))
        self.label_5.setText(_translate("MachineLearning", "Train Size"))
        self.txt_train_size.setPlaceholderText(_translate("MachineLearning", "Train Size"))
        self.btn_data_open.setText(_translate("MachineLearning", "Data Processing"))
        self.btn_ml_prediction_open.setText(_translate("MachineLearning", "Machine Learning Prediction"))
        self.btn_ml_open.setText(_translate("MachineLearning", "Machine Learning"))

