# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.parameter_frame = QtWidgets.QFrame(MainWindow)
        self.parameter_frame.setGeometry(QtCore.QRect(40, 10, 411, 181))
        self.parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameter_frame.setObjectName("parameter_frame")
        self.label_load_2 = QtWidgets.QLabel(self.parameter_frame)
        self.label_load_2.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_load_2.setObjectName("label_load_2")
        self.echo_size = QtWidgets.QLineEdit(self.parameter_frame)
        self.echo_size.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.echo_size.setObjectName("echo_size")
        self.label_2 = QtWidgets.QLabel(self.parameter_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.noise_size = QtWidgets.QLineEdit(self.parameter_frame)
        self.noise_size.setGeometry(QtCore.QRect(120, 110, 113, 21))
        self.noise_size.setObjectName("noise_size")
        self.label_3 = QtWidgets.QLabel(self.parameter_frame)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.parameter_frame)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_4.setObjectName("label_4")
        self.sample_frequency = QtWidgets.QComboBox(self.parameter_frame)
        self.sample_frequency.setGeometry(QtCore.QRect(120, 30, 104, 26))
        self.sample_frequency.setObjectName("sample_frequency")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.files_frame = QtWidgets.QFrame(MainWindow)
        self.files_frame.setGeometry(QtCore.QRect(40, 210, 411, 501))
        self.files_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.files_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.files_frame.setObjectName("files_frame")
        self.label_load = QtWidgets.QLabel(self.files_frame)
        self.label_load.setGeometry(QtCore.QRect(10, 20, 76, 16))
        self.label_load.setObjectName("label_load")
        self.btn_load_file = QtWidgets.QPushButton(self.files_frame)
        self.btn_load_file.setGeometry(QtCore.QRect(90, 10, 171, 32))
        self.btn_load_file.setObjectName("btn_load_file")
        self.table_widget = QtWidgets.QTableWidget(self.files_frame)
        self.table_widget.setGeometry(QtCore.QRect(0, 130, 401, 511))
        self.table_widget.setMinimumSize(QtCore.QSize(401, 0))
        self.table_widget.setMaximumSize(QtCore.QSize(401, 16777215))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(5)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(4, item)
        self.btn_save_echo = QtWidgets.QPushButton(self.files_frame)
        self.btn_save_echo.setGeometry(QtCore.QRect(80, 80, 181, 32))
        self.btn_save_echo.setObjectName("btn_save_echo")
        self.echo_file_name = QtWidgets.QLineEdit(self.files_frame)
        self.echo_file_name.setGeometry(QtCore.QRect(140, 50, 113, 21))
        self.echo_file_name.setObjectName("echo_file_name")
        self.label = QtWidgets.QLabel(self.files_frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(MainWindow)
        self.scrollArea.setGeometry(QtCore.QRect(470, 10, 881, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea_widget = QtWidgets.QWidget()
        self.scrollArea_widget.setGeometry(QtCore.QRect(0, 0, 879, 419))
        self.scrollArea_widget.setObjectName("scrollArea_widget")
        self.scrollArea.setWidget(self.scrollArea_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_load_2.setText(_translate("MainWindow", "Initial Parameters"))
        self.echo_size.setText(_translate("MainWindow", "1024"))
        self.label_2.setText(_translate("MainWindow", "Echo size"))
        self.noise_size.setText(_translate("MainWindow", "350"))
        self.label_3.setText(_translate("MainWindow", "Noise size"))
        self.label_4.setText(_translate("MainWindow", "Echo size"))
        self.sample_frequency.setItemText(0, _translate("MainWindow", "2.86MHz"))
        self.sample_frequency.setItemText(1, _translate("MainWindow", "1.14MHz"))
        self.sample_frequency.setItemText(2, _translate("MainWindow", "114KHz"))
        self.label_load.setText(_translate("MainWindow", "Select File"))
        self.btn_load_file.setText(_translate("MainWindow", "Load Files"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Distance"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File"))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Add Plot"))
        item = self.table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Folder"))
        self.btn_save_echo.setText(_translate("MainWindow", "Save echo to file"))
        self.label.setText(_translate("MainWindow", "Echo file name"))

