# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 855)
        self.parameter_frame = QtWidgets.QFrame(MainWindow)
        self.parameter_frame.setGeometry(QtCore.QRect(20, 50, 421, 181))
        self.parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameter_frame.setObjectName("parameter_frame")
        self.label_load_2 = QtWidgets.QLabel(self.parameter_frame)
        self.label_load_2.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_load_2.setObjectName("label_load_2")
        self.label_2 = QtWidgets.QLabel(self.parameter_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.parameter_frame)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.parameter_frame)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_4.setObjectName("label_4")
        self.sample_frequency = QtWidgets.QComboBox(self.parameter_frame)
        self.sample_frequency.setGeometry(QtCore.QRect(120, 30, 104, 26))
        self.sample_frequency.setObjectName("sample_frequency")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.sample_frequency.addItem("")
        self.echo_size = QtWidgets.QLabel(self.parameter_frame)
        self.echo_size.setGeometry(QtCore.QRect(120, 70, 81, 16))
        self.echo_size.setObjectName("echo_size")
        self.noise_size = QtWidgets.QLabel(self.parameter_frame)
        self.noise_size.setGeometry(QtCore.QRect(120, 110, 81, 16))
        self.noise_size.setObjectName("noise_size")
        self.files_frame = QtWidgets.QFrame(MainWindow)
        self.files_frame.setGeometry(QtCore.QRect(20, 240, 421, 571))
        self.files_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.files_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.files_frame.setObjectName("files_frame")
        self.label_load = QtWidgets.QLabel(self.files_frame)
        self.label_load.setGeometry(QtCore.QRect(10, 20, 76, 16))
        self.label_load.setObjectName("label_load")
        self.btn_load_file = QtWidgets.QPushButton(self.files_frame)
        self.btn_load_file.setGeometry(QtCore.QRect(90, 10, 251, 32))
        self.btn_load_file.setObjectName("btn_load_file")
        self.table_widget = QtWidgets.QTableWidget(self.files_frame)
        self.table_widget.setGeometry(QtCore.QRect(10, 150, 401, 401))
        self.table_widget.setMinimumSize(QtCore.QSize(401, 0))
        self.table_widget.setMaximumSize(QtCore.QSize(401, 16777215))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(5)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(4, item)
        self.btn_save_echo = QtWidgets.QPushButton(self.files_frame)
        self.btn_save_echo.setGeometry(QtCore.QRect(80, 80, 261, 32))
        self.btn_save_echo.setObjectName("btn_save_echo")
        self.echo_file_name = QtWidgets.QLineEdit(self.files_frame)
        self.echo_file_name.setGeometry(QtCore.QRect(140, 50, 191, 21))
        self.echo_file_name.setObjectName("echo_file_name")
        self.label = QtWidgets.QLabel(self.files_frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label.setObjectName("label")
        self.signal_frame = QtWidgets.QFrame(MainWindow)
        self.signal_frame.setGeometry(QtCore.QRect(460, 50, 391, 381))
        self.signal_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signal_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signal_frame.setObjectName("signal_frame")
        self.label_5 = QtWidgets.QLabel(self.signal_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.signal_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 371, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.signal_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.signal_box.setContentsMargins(0, 0, 0, 0)
        self.signal_box.setObjectName("signal_box")
        self.plot_index = QtWidgets.QComboBox(self.signal_frame)
        self.plot_index.setGeometry(QtCore.QRect(150, 10, 151, 26))
        self.plot_index.setObjectName("plot_index")
        self.fft_frame = QtWidgets.QFrame(MainWindow)
        self.fft_frame.setGeometry(QtCore.QRect(460, 440, 821, 361))
        self.fft_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fft_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fft_frame.setObjectName("fft_frame")
        self.label_7 = QtWidgets.QLabel(self.fft_frame)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.fft_frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 801, 321))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.fft_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.fft_box.setContentsMargins(0, 0, 0, 0)
        self.fft_box.setObjectName("fft_box")
        self.signal_frame_2 = QtWidgets.QFrame(MainWindow)
        self.signal_frame_2.setGeometry(QtCore.QRect(860, 50, 421, 381))
        self.signal_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signal_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signal_frame_2.setObjectName("signal_frame_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.signal_frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 401, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.echo_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.echo_box.setContentsMargins(0, 0, 0, 0)
        self.echo_box.setObjectName("echo_box")
        self.label_6 = QtWidgets.QLabel(self.signal_frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_6.setObjectName("label_6")
        self.btn_data_open = QtWidgets.QPushButton(MainWindow)
        self.btn_data_open.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.btn_data_open.setObjectName("btn_data_open")
        self.btn_ml_prediction_open = QtWidgets.QPushButton(MainWindow)
        self.btn_ml_prediction_open.setGeometry(QtCore.QRect(450, 10, 251, 32))
        self.btn_ml_prediction_open.setObjectName("btn_ml_prediction_open")
        self.btn_ml_open = QtWidgets.QPushButton(MainWindow)
        self.btn_ml_open.setGeometry(QtCore.QRect(220, 10, 241, 32))
        self.btn_ml_open.setObjectName("btn_ml_open")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_load_2.setText(_translate("MainWindow", "Initial Parameters"))
        self.label_2.setText(_translate("MainWindow", "Echo size"))
        self.label_3.setText(_translate("MainWindow", "Noise size"))
        self.label_4.setText(_translate("MainWindow", "Echo size"))
        self.sample_frequency.setItemText(0, _translate("MainWindow", "2.86MHz"))
        self.sample_frequency.setItemText(1, _translate("MainWindow", "1.14MHz"))
        self.sample_frequency.setItemText(2, _translate("MainWindow", "114KHz"))
        self.echo_size.setText(_translate("MainWindow", "4096"))
        self.noise_size.setText(_translate("MainWindow", "0"))
        self.label_load.setText(_translate("MainWindow", "Select File"))
        self.btn_load_file.setText(_translate("MainWindow", "Load Files"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File"))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Folder"))
        item = self.table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Add Plot"))
        self.btn_save_echo.setText(_translate("MainWindow", "Save Echo"))
        self.label.setText(_translate("MainWindow", "Echo file name"))
        self.label_5.setText(_translate("MainWindow", "Time Domain Chart"))
        self.label_7.setText(_translate("MainWindow", "FFT Chart"))
        self.label_6.setText(_translate("MainWindow", "Echo Chart"))
        self.btn_data_open.setText(_translate("MainWindow", "Data Processing"))
        self.btn_ml_prediction_open.setText(_translate("MainWindow", "Machine Learning Prediction"))
        self.btn_ml_open.setText(_translate("MainWindow", "Machine Learning"))

